groups:
  - name: example-alert
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "Target {{ $labels.job }} ({{ $labels.instance }}) is not responding."
